name: build_ErfanGSIs

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://objects.githubusercontent.com/github-production-release-asset-2e65be/362393580/6c656375-7191-4e6b-bae1-daf57bb3bfa1?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20221105%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20221105T163926Z&X-Amz-Expires=300&X-Amz-Signature=1702ed9b07bf2adeeb3b3f4d91306d8d91f17d66c989995011c2b45fc2079488&X-Amz-SignedHeaders=host&actor_id=117448159&key_id=0&repo_id=362393580&response-content-disposition=attachment%3B%20filename%3DPixelExperience_arm64-ab-13.0-20221104-UNOFFICIAL.img.xz&response-content-type=application%2Foctet-stream
  ROM_NAME: Pixel
  BUILD_TYPE: ab
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq install git wget curl g++ 
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git ErfanGSIs
         
       - name: Fix exit
         run: |
              sed -i 's/\|\| exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
              sed -i 's/exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
       
       - name: Setting up ErfanGSI requirements with XiaoxinSGSI setup script
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs
              mkdir ./output
              sudo bash ./setup.sh
              
       - name: Download Stock Rom & Generate GSI
         run: |
             cd $GITHUB_WORKSPACE/ErfanGSIs
             sudo bash ./url2GSI.sh -c --$BUILD_TYPE $ROM_URL $ROM_NAME

       - name: 7Zip GSI  
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs/output
              mkdir upload
              7za a -t7z -r GSI.7z ./*
              if [[ $(du -sb "GSI.7z" | awk '{print $1}') -gt 2097152000 ]];then
                  echo -e "split packaging..."
                  tar -cpzf - "GSI.7z" | split -d -b 1024m - "upload/GSI.7z"
              else
                  mv GSI.7z upload/
              fi
              ls "upload"                  
              
       - name: Upload SGSI to action-release...
         uses: ncipollo/release-action@v1.8.6
         with:
           artifacts: ${{ github.workspace }}/ErfanGSIs/output/upload/*
           name: ErfanGSIs-${{ env.ROM_NAME }}-${{ env.BUILD_TYPE }}
           tag: ErfanGSIs-${{ env.ROM_NAME }}-${{ env.BUILD_TYPE }}-${{ github.run_number }}
           token: ${{ secrets.GITHUB_TOKEN }}
